Implementing custom_request_headers
terraform-google-modules/terraform-google-lb-http pull request #122
Opened 2020-09-18 14:13 UTC by femrtnz

(Optional) Headers that the HTTP/S load balancer should add to proxied requests.

https://cloud.google.com/load-balancing/docs/custom-headers#variables
https://www.terraform.io/docs/providers/google/r/compute_backend_service.html

2020-09-18 14:49 UTC, femrtnz commented
If someone could point out what is failing I'm happy to fix it :)

2020-09-22 04:37 UTC, morgante requested changes
Thanks for the contribution.

You'll need to add `custom_request_headers = null` in all the existing examples.

2020-09-22 04:37 UTC, morgante commented on examples/multi-backend-multi-mig-bucket-https-lb/main.tf
>        health_check                    = local.health_check
Please run `terraform fmt`.

```suggestion
      health_check = local.health_check
```

2020-09-22 08:39 UTC, femrtnz commented on examples/multi-backend-multi-mig-bucket-https-lb/main.tf
>        health_check                    = local.health_check
Thanks!

2020-09-22 10:20 UTC, femrtnz commented
> Thanks for the contribution.
> 
> You'll need to add `custom_request_headers = null` in all the existing examples.

Hi @morgante thanks for the message. Please let me know if there are anything else to change.

2020-09-22 16:06 UTC, morgante commented
@femrtnz Looks like you missed one example: terraform_validate ./examples/https-redirect

2020-09-22 16:15 UTC, femrtnz commented
> @femrtnz Looks like you missed one example: terraform_validate ./examples/https-redirect

hi @morgante 

Actually I add this already here: https://github.com/terraform-google-modules/terraform-google-lb-http/pull/122/files#diff-61e9ef05efa9836976128999f5f1ddbbL114

Am I missing something?

2020-09-22 16:27 UTC, morgante commented
@femrtnz You also need to add `iap_config = null` to that module. It looks like we missed it earlier.

2020-09-22 17:01 UTC, femrtnz commented
> @femrtnz You also need to add `iap_config = null` to that module. It looks like we missed it earlier.

Hey @morgante , sure thing. Just pushed the missing field.

Thanks

2020-09-22 17:36 UTC, morgante commented
@femrtnz Linter is still failing. Could you please test locally and get things working? We explain how here: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/CONTRIBUTING.md

2020-10-05 14:14 UTC, femrtnz commented
Hi @morgante Just fixed the Linter :)

Please let me know if you have any questions.

Thanks

2020-10-05 15:43 UTC, morgante approved these changes

2020-10-05 15:44 UTC, merged

2020-10-08 15:16 UTC, naseemkullah commented
@morgante can we cut a release with this feature please?