feat: add support for https only procotol in NEG backend service
terraform-google-modules/terraform-google-lb-http pull request #205
Opened 2021-08-24 14:22 UTC by gangsta

As per discussion in https://github.com/terraform-google-modules/terraform-google-lb-http/issues/201

I have created basic changes to the module, please let me know if there is a better way of doing it.
I checked some different scenarios and come up with the following changes, which will allow
* to support only HTTPS or HTTP2 backend services.

I'm up for changes If this doesn't fit your current workstyle/module style.

2021-08-25 09:24 UTC, gangsta commented on autogen/main.tf.tmpl
> +
I would love to have here extra :eyes: .
should we move this default to variables? or leave it here?

one more thing: each.value.port_name vs lookup(each.value, "port_name", "HTTP")

which one is better ?

2021-09-07 16:56 UTC, morgante requested changes
Thanks for the contribution!

2021-09-09 14:32 UTC, gangsta commented on autogen/variables.tf.tmpl
>    type = map(object({
awesome let me fix it :+1: 

Thanks for helping out here

2021-09-09 14:54 UTC, gangsta commented on autogen/variables.tf.tmpl
>    type = map(object({
oh now I see what u refer to.
according to this: https://www.terraform.io/docs/language/expressions/types.html

block of 85-148 line should be changed to type map

is that correct ?

2021-09-09 14:59 UTC, morgante commented on autogen/variables.tf.tmpl
>    type = map(object({
It should be changed to `map(any)`.

2021-09-10 07:16 UTC, gangsta commented on autogen/variables.tf.tmpl
>    type = map(object({
I have added map(any) but ci is failing, is there a chance to see what is error so I can fix it?

2021-09-10 15:46 UTC, morgante commented on autogen/variables.tf.tmpl
>    type = map(object({
The error is commented above ^^^

2021-11-15 10:27 UTC, gangsta commented
Hi @morgante .
here is example of setup we want to accomplish.

The current setup is by default creating `HTTP only` or `HTTP and HTTPS` protocols for NEG. But in my case, we need only `HTTPS only`.

config example is going to be 

```
module "neg_external" {
  source               = "GoogleCloudPlatform/lb-http/google//modules/serverless_negs"
  version              = "~> 5.1"
  name                 = "neg-external"
  project              = var.project_id
  ssl                  = true
  ssl_certificates     = ["projects/someproject-here/global/sslCertificates/wildcard-certificate"]
  use_ssl_certificates = true
  http_forward         = false
  create_address       = false
  address              = "someiphere"

  backends = {
    default = {
      description                     = null
      protocol                        = "HTTPS"
      port                            = 443
      port_name                       = "https"
      timeout_sec                     = 300
      connection_draining_timeout_sec = 60
      enable_cdn                      = false
      security_policy                 = google_compute_security_policy.allow_some_policy.self_link
      session_affinity                = null
      affinity_cookie_ttl_sec         = null
      custom_request_headers          = null
      custom_response_headers         = null

      log_config = {
        enable      = true
        sample_rate = null
      }

      groups = [
        {
          group                        = google_compute_region_network_endpoint_group.some_neg.id
          balancing_mode               = null
          capacity_scaler              = null
          description                  = null
          max_connections              = null
          max_connections_per_instance = null
          max_connections_per_endpoint = null
          max_rate                     = null
          max_rate_per_instance        = null
          max_rate_per_endpoint        = null
          max_utilization              = null
        }
      ]
      iap_config = {
        enable               = false
        oauth2_client_id     = ""
        oauth2_client_secret = ""
      }
    }
  }
}
```

2022-02-28 10:23 UTC, gangsta commented
Still active

2022-05-05 18:09 UTC, kkirpichnikov commented
@morgante any plans to review and merge it?

2022-07-13 23:19 UTC, closed without merging