Support for multiple Backend Storage Buckets with Examples
terraform-google-modules/terraform-google-lb-http pull request #226
Opened 2021-12-07 21:40 UTC by wapfel

Adds functionality to host static website content behind a HTTP lb using one or more Cloud Storage Buckets, with the option to enable CDN on them. Also includes 2 examples, one just using an IP over http and another using a custom domain, https, and ssl.

2021-12-07 23:20 UTC, morgante requested changes

2021-12-07 23:20 UTC, morgante commented on examples/static-website-with-no-domain/main.tf
> +    "cdn_policy" = {
Let's just use defaults.

2021-12-07 23:20 UTC, morgante commented on modules/backend_bucket/README.md
> +## Version
Let's remove this section since it's not applicable here.

2021-12-07 23:20 UTC, morgante commented on examples/static-website-with-no-domain/main.tf
> +module "load-balancer-sslcert-CDN" {
```suggestion
module "load-balancer" {
```

2021-12-07 23:20 UTC, morgante commented on modules/backend_bucket/variables.tf
> +variable "backends" {
Let's call this buckets, not backends.

2021-12-08 22:15 UTC, wapfel commented on autogen/variables.tf.tmpl
>  variable "cdn" {
I'm not against this, but it does for a "one-size fits all" model for multiple buckets. Do you see a situation where a user would want to create multiple backend buckets, but only enable cdn on a subset of them? I built it for this scenario by having the cdn bool passed with the bucket object, but if it's not a common scenario, then we can do this instead.

2021-12-08 22:28 UTC, morgante commented on autogen/variables.tf.tmpl
>  variable "cdn" {
"YAGNI" - my initial assumption is consistent CDN settings across all buckets. We can always add tailored settings later if customer demand comes up.

2021-12-09 20:06 UTC, wapfel commented on examples/static-website-with-domain-ssl/README.md
> +You can tweak this example to enable other functionalities such as:
What specifically is this comment referring to, line 7 or line 9?

2021-12-09 20:09 UTC, wapfel commented on examples/static-website-with-domain-ssl/main.tf
> +  #instruction to create website storage bucket first
that was just a dev comment on why I used the "depends_on" there. I have removed it.

2021-12-09 22:12 UTC, wapfel commented on examples/static-website-with-domain-ssl/README.md
> +5. Update the name servers in your domain registry to point to the Cloud DNS zone's name servers provided in the output.
yes, they could always test directly via IP over port 443. Good point.

2021-12-09 22:13 UTC, wapfel commented on examples/static-website-with-domain-ssl/main.tf
> +    "cdn_policy" = {
I tried to remove these, but it caused problems with the way I build my object. This is another thing we may need to discuss a bit further.

2021-12-09 22:14 UTC, wapfel commented on examples/static-website-with-domain-ssl/README.md
> +4. Upload the provided site files to the cloud storage bucket. Visit the output bucket url of the storage bucket.
good point. I'll make the change shortly and remove that from the steps. Thanks for pointing out.

2021-12-10 21:15 UTC, wapfel commented on examples/static-website-with-domain-ssl/README.md
> +4. Upload the provided site files to the cloud storage bucket. Visit the output bucket url of the storage bucket.
change applied and steps updated in the readme.

2021-12-10 21:17 UTC, wapfel commented on examples/static-website-with-domain-ssl/main.tf
> +module "load-balancer-sslcert-CDN" {
updated

2022-01-05 21:04 UTC, morgante commented on examples/static-website-with-domain-ssl/README.md
> +You can tweak this example to enable other functionalities such as:
Line 9 (and the bullets below it).

2022-02-01 00:28 UTC, morgante requested changes
Many of my comments remain unaddressed. Kindly address previous feedback before requesting a new review.

2022-02-01 00:28 UTC, morgante commented on examples/static-website-with-domain-ssl/README.md
> +You can tweak this example to enable other functionalities such as:
@wapfel Just remove lines 9–13 or move them to the module README.

2022-02-01 00:28 UTC, morgante commented on examples/static-website-with-domain-ssl/README.md
> +3. Deploy only the storage bucket, since it must be created before referencing it to the load balancer:
You need to remove the targeted applies from the examples. There is something wrong with your approach if this is required.

Please check with me offline if you are confused about how to fix this.

2022-02-01 00:28 UTC, morgante commented on examples/static-website-with-domain-ssl/main.tf
> +    "cdn_policy" = {
Sounds like a bug. If you are confused, you can ping me on chat.

2022-04-09 23:17 UTC, closed without merging